cask_args appdir: '/Applications'

brew 'streamlink'
brew 'sqlite'
brew 'ruby'
brew 'rust'
brew 'lazygit'
brew 'yt-dlp'
brew 'atuin'
brew 'powerlevel10k'
brew 'neovim'
brew 'opencode'
brew 'zsh-syntax-highlighting'
brew 'tree-sitter'

cask 'telegram'
cask 'zed'
cask 'vlc'
cask 'alfred'
cask 'spotify'
cask 'iterm2'
cask 'handbrake-app'
cask 'whatsapp'
cask 'thunderbird'
cask 'discord'
cask 'steam'
cask 'bitwarden'
